function ratioOfStandardDeviations=calculateRatioOfStandardDeviations(CurrentStandardDeviation,PreviousStandardDeviation)

ratioOfStandardDeviations=[CurrentStandardDeviation(1)/PreviousStandardDeviation(1),CurrentStandardDeviation(2)/PreviousStandardDeviation(2),CurrentStandardDeviation(3)/PreviousStandardDeviation(3)];

end